/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kemahasiswaan_10119038_10119039.project;
import java.awt.Component;
import javax.swing.UIManager;
/**
 *
 * @author diky
 */
public class frm_utama extends javax.swing.JFrame {

    /**
     * Creates new form frm_utama
     */
    public frm_utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btn_dataMhs = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_dataMK = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_dataNilai = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btn_dataNA = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btn_dataSK = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Kemahasiswaan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jToolBar1.setRollover(true);

        btn_dataMhs.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_dataMhs.setForeground(new java.awt.Color(51, 51, 51));
        btn_dataMhs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10119038_10119039/gambar/student_50px-removebg-preview.png"))); // NOI18N
        btn_dataMhs.setText("Data Mahasiswa");
        btn_dataMhs.setFocusable(false);
        btn_dataMhs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dataMhs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_dataMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dataMhsActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_dataMhs);
        jToolBar1.add(jSeparator1);

        btn_dataMK.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_dataMK.setForeground(new java.awt.Color(51, 51, 51));
        btn_dataMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10119038_10119039/gambar/books_50px-removebg-preview.png"))); // NOI18N
        btn_dataMK.setText("Data Mata Kuliah");
        btn_dataMK.setFocusable(false);
        btn_dataMK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dataMK.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_dataMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dataMKActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_dataMK);
        jToolBar1.add(jSeparator2);

        btn_dataNilai.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_dataNilai.setForeground(new java.awt.Color(51, 51, 51));
        btn_dataNilai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10119038_10119039/gambar/note_50px-removebg-preview.png"))); // NOI18N
        btn_dataNilai.setText("Data Nilai");
        btn_dataNilai.setFocusable(false);
        btn_dataNilai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dataNilai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_dataNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dataNilaiActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_dataNilai);
        jToolBar1.add(jSeparator3);

        btn_dataNA.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_dataNA.setForeground(new java.awt.Color(51, 51, 51));
        btn_dataNA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10119038_10119039/gambar/contract_50px-removebg-preview.png"))); // NOI18N
        btn_dataNA.setText("Simulasi Nilai Akhir");
        btn_dataNA.setFocusable(false);
        btn_dataNA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dataNA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_dataNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dataNAActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_dataNA);
        jToolBar1.add(jSeparator4);

        btn_dataSK.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_dataSK.setForeground(new java.awt.Color(51, 51, 51));
        btn_dataSK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10119038_10119039/gambar/doughnut_50px-removebg-preview.png"))); // NOI18N
        btn_dataSK.setText("Simulasi Kasus");
        btn_dataSK.setFocusable(false);
        btn_dataSK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dataSK.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_dataSK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dataSKActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_dataSK);
        jToolBar1.add(jSeparator5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 410, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Tentang Pembuat");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dataMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dataMhsActionPerformed
        frm_mhs mhs = new frm_mhs();
        mhs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_dataMhsActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
         frm_utama utama = new frm_utama();
         utama.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btn_dataNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dataNilaiActionPerformed
        frm_nilai nilai = new frm_nilai();
        nilai.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_dataNilaiActionPerformed

    private void btn_dataMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dataMKActionPerformed
        frm_mataKuliah mk = new frm_mataKuliah();
        mk.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_dataMKActionPerformed

    private void btn_dataSKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dataSKActionPerformed
        
    }//GEN-LAST:event_btn_dataSKActionPerformed

    private void btn_dataNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dataNAActionPerformed
        frm_nilaiAkhir na = new frm_nilaiAkhir();
        na.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_dataNAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dataMK;
    private javax.swing.JButton btn_dataMhs;
    private javax.swing.JButton btn_dataNA;
    private javax.swing.JButton btn_dataNilai;
    private javax.swing.JButton btn_dataSK;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
